{{- if and .Values.featureGates.enableSpokeClusterCRD .Values.clusterCore.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubevela.fullname" . }}-cluster-core-admission
  namespace: {{ .Release.Namespace }}
  {{- if .Values.admissionWebhooks.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "kubevela.fullname" .) | quote }}
  {{- end }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "kubevela.fullname" . }}-cluster-core-webhook
        namespace: {{ .Release.Namespace }}
        path: /validating-core-oam-dev-v1beta1-spokeclusters
    failurePolicy: {{ .Values.admissionWebhooks.failurePolicy }}
    name: validating.core.oam.dev.v1beta1.spokeclusters
    sideEffects: None
    admissionReviewVersions:
      - v1beta1
      - v1
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - spokeclusters
    timeoutSeconds: {{ .Values.admissionWebhookTimeout }}
{{- end -}}
